import React from 'react';
import { SocialIcon } from 'react-social-icons';

const About = () => {
    return (
        <div className="About" >
            <h1 style={{ marginLeft: 10, textAlign: "center", color: "red" }}>Ibrahim Mohamed</h1>
            <div style={{ textAlign: "center", margin: 0 }}>
                <a target="_blank"><SocialIcon url="https://github.com/Ibrahim-Mohamed1" bgColor="white" fgColor="red" style={{ margin: 10 }} network="github" /></a>
                <a target="_blank"><SocialIcon url="https://www.linkedin.com/in/ibrahim-mohamed-" bgColor="white" fgColor="red" style={{ margin: 10 }} network="linkedin" /></a>
            </div>
            <p style={{ marginLeft: 10, marginRight: 10 }}>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ullam quidem, iure earum perferendis temporibus rerum quos aspernatur natus distinctio architecto, atque libero adipisci corporis excepturi quo enim repellat consequuntur est reprehenderit omnis. Obcaecati quidem quasi atque exercitationem maiores voluptatum, dolorem ea sapiente. Facere provident, fugit autem, similique vel dolore in eos consequuntur non natus officia, inventore officiis sint quos nesciunt numquam accusamus? Tempora consequatur expedita explicabo ratione ipsum aspernatur ab! Facere et, ex dolor magni doloremque molestias eos delectus pariatur porro qui laboriosam! Reiciendis ipsam alias itaque corporis laudantium fugiat tenetur ex molestiae inventore rerum sed ut eius hic, numquam quia repellendus enim laboriosam reprehenderit! Unde obcaecati tempora odio commodi impedit perferendis aut repellendus aperiam perspiciatis, veritatis quos, ratione atque, numquam aliquid velit quo fugit saepe modi explicabo nesciunt rem? Sequi labore enim praesentium nisi consectetur placeat veniam odit assumenda, eum, debitis consequuntur. Amet culpa laboriosam enim non aspernatur odio eius voluptates? Placeat porro praesentium libero alias ipsam temporibus dolor commodi molestiae. Omnis, repudiandae quos quia doloribus ad minus asperiores at tempore exercitationem optio assumenda qui recusandae! Accusamus facilis impedit, aut perspiciatis asperiores quae quisquam cum doloremque iusto? Dicta reprehenderit officia culpa ducimus repellat provident eveniet veritatis odio incidunt. Consequatur.
            </p>
            <h1 style={{ marginLeft: 10, textAlign: "center", color: "red" }}>Stuart Gardner</h1>
            <div style={{ textAlign: "center", margin: 0 }}>
                <a target="_blank"><SocialIcon url="https://github.com/Stgardner" bgColor="white" fgColor="red" style={{ margin: 10 }} network="github" /></a>
                <a target="_blank"><SocialIcon url="#" bgColor="white" fgColor="red" style={{ margin: 10 }} network="linkedin" /></a>
            </div>
            <p style={{ marginLeft: 10, marginRight: 10 }}>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt distinctio dolore provident fugiat voluptates quia, ea explicabo numquam vitae atque reiciendis ipsa consequatur iure quas. Consectetur cum sit molestiae ipsam explicabo odio deleniti numquam eveniet perspiciatis repellendus quasi commodi beatae facere dolor obcaecati repudiandae voluptatem totam, blanditiis dolorem optio? Mollitia optio, eveniet incidunt sint quis labore iure vel asperiores repudiandae quod rem quas inventore, facilis excepturi dignissimos, ducimus placeat dolorum aliquam illo iste? Consectetur ea quibusdam quam reiciendis quis suscipit, reprehenderit, ipsum explicabo, nihil vitae neque placeat quas ex sint libero saepe illum laborum sit velit. Optio animi voluptatum placeat, consectetur atque vitae veritatis at inventore maxime ratione. Voluptatum, dolorem iusto a doloremque rerum repellat perferendis similique tempore unde facere nostrum animi mollitia numquam eveniet ducimus et laboriosam? Similique, id illum. Ipsum illo laborum tenetur sint, aliquam exercitationem delectus aliquid, itaque pariatur totam atque quisquam reiciendis molestiae similique non quibusdam. Deleniti soluta nisi cumque nihil, repudiandae doloribus quos aspernatur deserunt, illum ut corporis molestiae quam dolore laboriosam odit voluptatum neque consequatur, voluptatem vitae? Ut, nobis minima. Dicta consequuntur dolor, nobis aliquam, non facere molestiae sit delectus quod reiciendis cupiditate odit impedit repellendus quisquam explicabo eligendi, quibusdam inventore quis maxime vel.
            </p>
            <h1 style={{ marginLeft: 10, textAlign: "center" }}>Bill Violette</h1>
            <div style={{ textAlign: "center", margin: 0 }}>
                <a target="_blank"><SocialIcon url="#" bgColor="white" fgColor="gray" style={{ margin: 10 }} network="github" /></a>
                <a target="_blank"><SocialIcon url="#" bgColor="white" fgColor="gray" style={{ margin: 10 }} network="linkedin" /></a>
            </div>
            <p style={{ marginLeft: 10, marginRight: 10 }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus quaerat eos nulla dolor corporis sit necessitatibus perferendis beatae ad laboriosam nihil consequatur ea modi cumque labore distinctio expedita laudantium obcaecati debitis corrupti, tenetur ullam fugit? Fuga voluptatibus eaque velit quo praesentium debitis, molestiae earum corrupti et maxime? Consequuntur quae dicta obcaecati totam et ab animi aliquam libero ex nostrum ipsum, fugiat inventore, itaque iure? Accusantium laboriosam quam excepturi assumenda accusamus temporibus. Fugit aspernatur recusandae inventore neque distinctio perspiciatis aperiam in nemo atque quia. Recusandae dolores laborum minus voluptas, similique, atque consectetur eaque veritatis sed voluptates provident eveniet tenetur? Cumque eveniet doloribus, earum ex dolorem quasi alias nemo quod voluptatem, pariatur dolore sapiente quia, cupiditate quas nobis! Fuga quasi, nesciunt iusto, impedit vel repudiandae, minus quo mollitia magnam distinctio itaque dolore repellendus amet! Quidem eius vel rerum inventore provident? Perferendis placeat enim culpa inventore. Laboriosam debitis assumenda provident voluptatem sint, deleniti sequi hic voluptates facere illo facilis similique nemo aliquid odio quibusdam. Optio, non. Aspernatur fugiat dolores sed dolore iusto illum, quibusdam, maiores tempora doloribus blanditiis temporibus suscipit numquam at minus fugit consequuntur voluptatum cum libero totam? Esse in veritatis, laboriosam quam modi, harum assumenda deleniti molestiae perferendis voluptas, accusamus quibusdam.
            </p>
            <h1 style={{ marginLeft: 10, textAlign: "center" }}>Abhi Tiwari</h1>
            <div style={{ textAlign: "center", margin: 0 }}>
                <a target="_blank"><SocialIcon url="http://jaketrent.com" bgColor="white" fgColor="gray" style={{ margin: 10 }} network="github" /></a>
                <a target="_blank"><SocialIcon url="http://jaketrent.com" bgColor="white" fgColor="gray" style={{ margin: 10 }} network="linkedin" /></a>
            </div>
            <p style={{ marginLeft: 10, marginRight: 10 }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi minima impedit, facilis beatae cumque animi quis. Labore soluta voluptates officia est tempore illo dignissimos reiciendis, animi error expedita totam similique. Inventore eaque nobis quasi omnis neque odio facilis distinctio praesentium, ipsam, ratione deserunt dicta. Deleniti dolorum neque tenetur tempore molestiae animi possimus voluptatum est incidunt rerum, odio quod? Veniam fugit dolore dicta dolores accusamus. Amet beatae recusandae minima? Iste id dolores quas odit nobis sit quibusdam, nulla rem repellat voluptatem maxime magni voluptatibus eveniet? Repellat repellendus optio consequuntur laboriosam fuga, libero dolore neque eligendi. Earum doloribus laudantium magnam in temporibus cupiditate maiores praesentium, dolore sunt, repellat rerum iusto vel labore officia odit debitis a. Dolorum, quisquam. Totam ipsum, voluptates corporis natus illo expedita, similique dignissimos hic deserunt deleniti soluta labore quis quo at dolore ab obcaecati sit optio doloribus neque aliquam? Tenetur iure eligendi voluptas distinctio alias debitis explicabo quo numquam pariatur! Tempora id nisi, ut repudiandae blanditiis facere eveniet laudantium molestiae, aut aliquam quis accusamus corrupti maiores numquam dicta reiciendis laboriosam. Aliquam error iusto maxime? Ut voluptatibus aliquid dolores recusandae quam sint obcaecati molestiae laudantium maiores nulla, adipisci beatae perferendis, quaerat iusto sapiente magnam voluptate totam necessitatibus eius quas?
            </p>
            <h2 style={{ margin: "5px 10px", display: "inline-block" }}>Built with: <span style={{ fontSize: 15, color:"lime" }}> React, Node.js, MongoDB, Mongoose, Express, HTML, CSS, Javascript, Axios, Chart.js, Chartkick</span></h2>
            <br />
            <h2 style={{ margin: "15px 10px", display: "inline-block" }}>API's used: <span style={{ fontSize: 15, color:"lime" }}>newsapi.org & cryptocompare</span></h2>
        </div>
    );
};

export default About;